name: Ultimate Visuals
favicon: null
layout_spectrum: 0.01232
typography_spectrum: 0.7340121986344457
title: Ultimate Visuals
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#414042'
    - '#a7ce38'
    - '#000000'
    - '#00ff00'
    - '#808000'
  brandStrength: 0.375
  lightness: 0.625
  saturation: 0.9760578330606222
  rhythmicContrast: 0.25
purpose: []
